version: "3.7"
services:
  app:
    build:
      args:
        user: flashy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: flashy
    container_name: flashy-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - flashy

  nginx:
    image: nginx:alpine
    container_name: flashy-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
    networks:
      - flashy

networks:
  flashy:
    driver: bridge